version: "3"
services:
  client:
    stdin_open: true
    container_name: gif-expert-app
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - "app/node_modules"
      - ".:/app"
